### ISSUE TITLE
[BUG][V3.0] Module won't start

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#72]
I just clean installed Companion 3.0 and just added my dev path, then added the module inside companion.

But is just goes "Status: crashed"

Here's the log (this happens in a loop forever)

```
system: ** Connection started **
Starting up module class: BAirInstance
Sentry disabled
Module-host accepted registration
```
```
error: Failed to init: Error: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at BAirInstance.getConfigFields (file:///E:/Professional/Empire%20Media%20Science/Projects/Companion/companion-module-behringer-xair/index.js:756:14)
    at E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\@companion-module\base\dist\module-api\base.js:83:37
    at run (E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:157:104)
    at PQueue._tryToStartAnother (E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:105:17)
    at E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:171:18
    at new Promise (<anonymous>)
    at PQueue.add (E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:152:16)
    at BAirInstance._handleInit (E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\@companion-module\base\dist\module-api\base.js:73:37)
    at IpcWrapper.receivedMessage (E:\Professional\Empire Media Science\Projects\Companion\companion-module-behringer-xair\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:68:17)
```
```
system: ** Connection stopped **
```

Commit 52b0d345b079ed8dcc822b53287704d36c7b9c57

**Comment by Mozoloa** [comment]
Looks like I should npm update after each pulls, I did that and now it's working !
