### ISSUE TITLE
Crashing on startup after adding (this.getConfigFields is not a function)

### ISSUE THREAD

**Issue by zoton2** [bitfocus/companion-module-behringer-xair#90]
Adding this module, it's getting stuck in a crashing loop.

```
system: ** Starting Connection from "C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js" **
system: ** Connection started **
Starting up module class: b
Sentry disabled
Module-host accepted registration
error: Failed to init: Error: this.getConfigFields is not a function TypeError: this.getConfigFields is not a function
    at C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:610532
    at C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:503700
    at t.default._tryToStartAnother (C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:502747)
    at C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:503907
    at new Promise (<anonymous>)
    at t.default.add (C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:503550)
    at b._handleInit (C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:610366)
    at t.IpcWrapper.receivedMessage (C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:593959)
    at process.<anonymous> (C:\Program Files\Companion\resources\bundled-modules\behringer-xair\main.js:1:609850)
    at process.emit (node:events:517:28)
system: ** Connection stopped **
```

This is on a fresh install of the most recent stable BitFocus Companion (`3.3.0 (3.3.0+6991-stable-b27baf94)`).

Seems to be similar to #65 but that was a year ago and was fixed in #68, I guess something similar has cropped up again?

**EDIT:** Just to provide a better log, here's the same log but when I clone this repository and try to run it that way.

```
system: ** Starting Connection from "C:\prod_files\companion_dev_modules\companion-module-behringer-xair\index.js" **
system: ** Connection started **
Starting up module class: BAirInstance
Sentry disabled
Module-host accepted registration
error: Failed to init: Error: this.getConfigFields is not a function TypeError: this.getConfigFields is not a function
    at C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\@companion-module\base\dist\module-api\base.js:89:37
    at run (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:157:104)
    at PQueue._tryToStartAnother (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:105:17)
    at C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:171:18
    at new Promise (<anonymous>)
    at PQueue.add (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\p-queue\dist\index.js:152:16)
    at BAirInstance._handleInit (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\@companion-module\base\dist\module-api\base.js:79:37)
    at IpcWrapper.receivedMessage (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:72:17)
    at process.<anonymous> (C:\prod_files\companion_dev_modules\companion-module-behringer-xair\node_modules\@companion-module\base\dist\module-api\base.js:69:30)
    at process.emit (node:events:517:28)
system: ** Connection stopped **
```

**Comment by zoton2** [comment]
After some debugging, seems like in the latest commit `getConfigFields` was moved to it's own file, and was imported in the main file but not added to the class. After that is fixed, and the new file has another fix done (`Regex` needs importing from `@companion-module/base`), it starts up.

**Comment by istnv** [comment]
Not sure how that slipped by. I do use the module almost daily. :/

**Comment by zoton2** [comment]
I assume Companion only calls that function on first setup? Which would be why you didn't notice it.

**Comment by istnv** [comment]
It gets called every time you bring up the 'Config' tab. I had a pretty massive head cold that week. I wonder how many other 'stable' modules I broke :man_shrugging:
